---
apiVersion:       v1
kind:             Namespace
metadata:
  name:           kube-pdm
  labels:
    app:          kube-pdm
---
apiVersion:       v1
kind:             ConfigMap
metadata:
  name:           myindex
  namespace:      kube-pdm
data:
  index.html:   |
    Nginx V1.31.6
---
apiVersion:       v1
kind:             Pod
metadata:
  name:           kube-pdm-pod-nginx
  labels:
    app:          kube-pdm-nginx
  namespace:      kube-pdm
spec:
  containers:
  - name:         nginx
    image:        nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath:  /usr/share/nginx/html
      readOnly:   true
      name:       volumesnginx
  volumes:
    - name:         volumesnginx
      configMap:
        name:       myindex
        items:
        - key: index.html
          path: index.html
